### PR TITLE
Support to put multiple speakers in a session

### PR DESCRIPTION
**Pull request by YamazakiYasuhiro**
This feature will be needed by @sokky . ;-)

### CODE REVIEW

**Comment by sokky** [comment]
ありがとうございます！

**Comment by YamazakiYasuhiro** [comment]
pls merge if nothing is wrong.

**Comment by koudaiii** [comment]
Sorry ... I will check this pr :bow:

**Comment by YamazakiYasuhiro** [comment]
@sokky will be able to do it, i think. anyway i'm waiting for both of you!

**Comment by sokky** [comment]
チェックついでに二人のやつを追加します。いけそうならマージまでしちゃいます

**Comment by koudaiii** [comment]
Fix, yaml format.

Thank you for pr!!

I will merge 👍 
Please waiting build test 🙇

**Pull request merged**
